### ISSUE TITLE
Integrate renamings into NPG-->SNT analysis

### ISSUE THREAD

**Issue by martinmuellerma** [martinmuellerma/SN-T-mappings-to-PMCs-and-NPGs#2]
@canbekleyici  In column Z of the 
[ontology_2020-05-29_09-00-35.xlsx](https://github.com/martinmuellerma/SN-T-mappings-to-PMCs-and-NPGs/files/5161587/ontology_2020-05-29_09-00-35.xlsx)
SNT-Export I have notified whenever a NPG-subject has been renamed and is thus identical with the associated SNT, e.g. Amino Sugar, column Z: "NPG - completeness check - formerly: Amino Sugars". Can you take care of it classifying it by the match_type "renaming"?
@canbekleyici, I have created manually an example output (uppermost eight rows), which is filtered on no 'direct matches', see
[nature_subjects_to_snt_completed.xlsx](https://github.com/martinmuellerma/SN-T-mappings-to-PMCs-and-NPGs/files/5218041/nature_subjects_to_snt_completed.xlsx)

**Comment by canbekleyici** [comment]
Resolved in https://github.com/martinmuellerma/SN-T-mappings-to-PMCs-and-NPGs/commit/87e9ae8a2926ee8f9439c76f6b78eb810070818e
